### PR TITLE
Added svg icons of languages, fixed some css, grammar and added roboto fonts.

### PR DESCRIPTION
**Pull request by theNaut1lus**
This PR is a big one.
While I had set out to implement #27 I got a little carried away and implemented some more changes like the ones you will see in my branch.
1. added svg logos for all languages (could only find png for Matlab but resized to make it similar to an svg)
2. changed the list to a table to make a grid of options instead of a list causing the user to scroll
3. made some grammatical changes.
4. added robot font for the body texts
4. removed call to source sans pro as it was a redundant call and would have slowed down loading.
5. corresponding UI changes in CSS.

P.S: have for now not created class names for small elements assuming that they won't appear again in this splash page.

**Before**
Screenshot 2019-05-08 at 9 49 36 PM

**After**
Screenshot 2019-05-08 at 9 49 21 PM

P.P.S: Have plenty of ideas for new changes and all, will wait for this PR's resolution before working further.

/cc: @AnshulMalik

### CODE REVIEW

**Comment by AnshulMalik** [comment]
Nice work! Few things to mention though.

This is a perfect example to use css grids instead of tables :) And we'd ideally like to display vertically centered to the icon(it goes to the bottom of the icon currently).
And we'll probably won't need the border of the table.

Well done :)

**Comment by theNaut1lus** [comment]
@AnshulMalik 
We could use grids but that could cause unnecessary complications to the css, or if you agree on using a pre-defined grid library we could call it via a cdn which will only load the modules called in the code. What do you say. 😃 
P.S: I know that the primary library that comes to mind is bootstrap but there are far more better and lighter grid-only css libraries out there for us to choose from. 🔥

**Comment by AnshulMalik** [comment]
Please have a look at this article https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Basic_Concepts_of_Grid_Layout

We don't need those libraries at all :)

**Comment by theNaut1lus** [comment]
@AnshulMalik 
have made the required changes, please check.

Updated Screenshot:
Screenshot 2019-05-16 at 11 31 14 PM

**Comment by AnshulMalik** [comment]
This looks awesome :) 
Just one thought, the language icon and text look like they are separated by a large space and the text is closer to the other language's icon. Can we make it such that the language name is closer to it's icon? this would then be perfect :)

**Comment by theNaut1lus** [comment]
@AnshulMalik made the requested changes. 👍 
looks much cleaner now.

Screenshot 2019-05-17 at 2 07 36 PM

**Comment by AnshulMalik** [comment]
This is perfect :) And ready to merge :)
It would be cherry on cake, if we can make do something on hover on any language or it's icon.
May be slight darker background and make this whole box clickable. 

But that can be done in another PR, Love this :)

**Comment by theNaut1lus** [comment]
> It would be cherry on cake, if we can make do something on hover on any language or it's icon.

@AnshulMalik would love to work on this as well, look out for another issue and PR soon 😄

**Pull request merged**
