### PR TITLE
hyperlinked icons

### PR DESCRIPTION
**Pull request by aniketdvd**
Enables a user to click on icon of the language.

### CODE REVIEW

**Comment by gabru-md** [comment]
ref #31

**Review by gabru-md — APPROVED** [review]
thanks a lot 😄

**Comment by AnshulMalik** [comment]
I just noticed underline under the icon(image) it looks a bit odd, just the text should be underlined. :)

**Comment by Ramanpreet6262** [comment]
I can work on this issue

**Pull request merged**
